# Generated by Django 3.2.13 on 2022-07-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('AnsId', models.AutoField(primary_key=True, serialize=False)),
                ('Ans', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('CatId', models.AutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=100)),
                ('CatFramework', models.CharField(max_length=100)),
                ('CatLang', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='numberofVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nbBack', models.IntegerField(null=True)),
                ('nbFront', models.IntegerField(null=True)),
                ('nbDesigners', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('pubId', models.AutoField(primary_key=True, serialize=False)),
                ('pubsubject', models.CharField(max_length=255)),
                ('pub', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='AskApp.cat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('VoteId', models.AutoField(primary_key=True, serialize=False)),
                ('Positive', models.IntegerField(null=True)),
                ('Negative', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ans_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='AskApp.answers')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste', to='AskApp.posts')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=255, null=True)),
                ('Education', models.CharField(max_length=255, null=True)),
                ('Function', models.CharField(max_length=255, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('MobileNumber', models.IntegerField(null=True)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='pub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anspub', to='AskApp.posts'),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans', to=settings.AUTH_USER_MODEL),
        ),
    ]
