# Generated by Django 3.2.13 on 2022-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
