# Generated by Django 3.2.13 on 2022-04-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='pubId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='AskApp.posts'),
        ),
    ]
