# Generated by Django 3.2.13 on 2022-04-22 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AskApp', '0003_remove_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='UserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answers',
            name='pubId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AskApp.posts'),
        ),
    ]
