# Generated by Django 3.2.13 on 2022-04-22 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AskApp', '0005_alter_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='UserId',
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans', to=settings.AUTH_USER_MODEL),
        ),
    ]
