# Generated by Django 3.2.13 on 2022-04-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0006_auto_20220422_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='cat',
        ),
        migrations.AddField(
            model_name='cat',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='AskApp.posts'),
        ),
    ]
