# Generated by Django 3.2.13 on 2022-04-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0007_auto_20220422_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='pubId',
        ),
        migrations.AddField(
            model_name='posts',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='AskApp.answers'),
        ),
    ]
