# Generated by Django 3.2.13 on 2022-04-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0008_auto_20220422_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='pub',
        ),
        migrations.AddField(
            model_name='posts',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='AskApp.cat'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anssw', to='AskApp.answers'),
        ),
    ]
