# Generated by Django 3.2.13 on 2022-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0009_auto_20220422_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='pub_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
