# Generated by Django 3.2.13 on 2022-04-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0010_answers_pub_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='user_id',
        ),
    ]
