# Generated by Django 3.2.13 on 2022-04-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskApp', '0012_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='answer',
        ),
        migrations.AlterField(
            model_name='answers',
            name='pub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anspub', to='AskApp.posts'),
        ),
    ]
