# Generated by Django 3.2.13 on 2022-06-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AskApp', '0015_auto_20220505_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('VoteId', models.AutoField(primary_key=True, serialize=False)),
                ('Positive', models.IntegerField(null=True)),
                ('Negative', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ans_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='AskApp.answers')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste', to='AskApp.posts')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
